inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6.2
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

Metrics/BlockLength:
  Exclude:
    - lib/tasks/*
    - spec/graphql/*

Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
