inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    # - 'config/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120