inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    # - 'config/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Rails/HasAndBelongsToMany:
  Enabled: false
